@startuml
start
:下载数据;


partition 数据探索 {
fork
:数据描述方法;
:    最多（众值）
    平均（平均数）
    中间（中位数）
    最大（极值）
    最小（极值）
    浮动程度（方差）
    曲线形状（分布）;
fork again
:数理统计方法;
:假设检验
方差分析
相关分析
回归分析
因子分析;
end fork

}
partition 数据处理 {
:插值重采样;
:归一化;
}

:;
stop
@enduml
